### ISSUE TITLE
Add AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY aliases

### ISSUE THREAD

**Issue by blairdrummond** [StatCan/aaw-minio-credential-injector#3]
At the moment we inject the MINIO variables, but some systems like just plain old AWS-style environment variables.

Seems like this would be straightforward.

**Comment by brendangadd** [comment]
@blairdrummond Any examples of software we're supporting that expects those variables to be set in the env?

**Comment by blairdrummond** [comment]
This was closed by #4  , but to your question @brendangadd , the `aws.s3` R package (seems to be the dominant R S3 system), uses those variables.
